# Site settings
title: "Jenny He"
description: "Jenny He's personal website"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jenny He"
resume_title:                   "Fullstack Software Enginner"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "he.jie3@northeastern.edu"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "415-570-3410"
resume_contact_address:         "Milpitas, California"

resume_header_contact_info:     "Milpitas, California • 415-570-3410 • lhe.jie3@northeastern.edu"
display_header_contact_info:    "false"

resume_header_intro: "<p>As a dedicated full-stack engineer with a pronounced focus on front-end development, I am fueled by an unwavering passion for creating exceptional user experiences. With a robust foundation in web technologies, I adeptly blend artistic design with seamless functionality to craft captivating interfaces.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jennyhe-cam"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "linkedin.com/in/jiehe1120"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://jennyhe.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
